### ISSUE TITLE
What does Siderostat.fieldAngle return?

### ISSUE THREAD

**Issue by HojaeAhn** [sdss/lvmtipo#1]
Hi Florian,

While testing the position angle (=field angle?) calculating function, I found that the results from you and I are different.
So I want to make sure that what [fieldAngle] (https://github.com/sdss/lvmtipo/blob/14a72185b1d7ef9149b9325c778c53f215b09478/python/lvmtipo/siderostat.py#L67) returns. (What is the definition of field angle.)

Here is my code [cal_pa] 
(https://github.com/sdss/lvmagp/blob/8616df2e16e544cc0024475ae20fe8cb727fcfde/python/lvmagp/actor/internalfunc.py#L280).
It calculates the position angle based on the LVM coordinates document (0040 document). 

Can you check "fieldAngle" function returns the position angle as "cal_pa" function?

Also, I want to add additional information for you.
I tested both functions with same input : ra=5h, dec=0deg, lat=37.5960deg, long=127.0533deg.
The results were -0.026 deg for cal_pa and -127.306 deg for fieldAngle.
I selected the RA where the target is passing meridian when I tested. So I think cal_pa returns the position angle well.

**Comment by rmathar** [comment]
The code in lvmagp calculates the parallactic angle (which is the position angle of the zenith before the rays hit M1 of the siderostat, see https://en.wikipedia.org/wiki/Parallactic_angle). The code is not correct because it does not recognize the difference in the branches of the arctan. The fieldAngle() function in lvmtipo calculates the position angle '''after''' leaving the M2 and before hitting the K-mirrors (if there are any). fieldAngle() is the direction to the NCP measured clockwise (where ceiling=0) looking down the beam, _after_ M2. (Obviously it's also the position angle of the zenith, measured as usually ccw from the NCP.) Evidently these two values are different, because there are 2 tracking mirrors in between, and we do not have the lucky exception as for mirror trains fastened to an alt-az telescope that the parallactic angle survives these reflections. See e.g. https://wiki.sdss.org/download/attachments/18186530/LVM-0040_LVM%20Coordinates.pdf?api=v2
